name: Build Installer
on: release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build .exe
        run: pyinstaller --onefile --windowed --icon=assets/random.ico --add-data "assets/icon.ico;assets/" main.py
      - name: Install Inno Setup
        run: choco install innosetup -y
      - name: Build installer
        run: iscc randomChoice.iss
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: Output/RandomChoice.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
